### PR TITLE
#18 list repitition

### PR DESCRIPTION
**Pull request by LukasHolzner**
added list repetition to modeler and model creation. Also added nested list scraping functionality (should have been implemented with #7). This is already adjusted to repetition.

### CODE REVIEW

**Comment by LukasHolzner** [comment]
nested list scraping is still not working 100%, but is in work.

**Comment by LukasHolzner** [comment]
To be sure we are talking about the same issue. Nested list look like the following in html:
```[html]
<ul> <!-- parent list -->
<li>Text
    <ul> <!-- nested list -->
        <li>Subebene1 Text1</li>
        <li>Subebene1 Text2</li>
    </ul>
</li>
<li>Text2</li>
</ul>
```
now you can have 4 different scenarios:
1. both lists are repetitive (I think this ist the most/only variant)
2. both are non-repetitive
3. parent list is repetitive and nested is not
4. parent is not repetitive but nested is

some (all?) scenarios currently throw exceptions. I was able to fix the first scenario (not yet commited), but as I can't imagine examples for the other three scenarios, it is very difficult for me to implement the creation of the output dict for them.
maybe you (@julhac, @Macmueller) can give examples for all four combinations mentiond above and how the output sould look like. Thanks in advance.

**Comment by LukasHolzner** [comment]
@Macmueller please check again. I fixed the creation of all types of lists as mentioned above.

**Comment by Macmueller** [comment]
I found a small bug using the load feature, but is will address this in another issue. From my point this is ready to merge.

**Comment by LukasHolzner** [comment]
alright, then I merge this and check for the bug afterwards. I can't explain this because I thought I already checked and fixed...

**Pull request merged**
